version: '3.2'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
      - INFLUXDB_DB=gatlingdb
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
  grafana:
    build: grafana
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'

volumes:
  influxdb-storage:
  chronograf-storage: